import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import "@mantine/core/styles.css"
import Providers from "@/app/providers";
import {ColorSchemeScript} from "@mantine/core";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mantine + Tailwind example',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
