import type { Metadata } from 'next'
import {Instrument_Sans, Montserrat} from 'next/font/google'
// BEFORE Tailwind styles import
import "@mantine/core/styles.css"
import '@mantine/carousel/styles.css';

// ALWAYS after Mantine
import './globals.css'
import Providers from "@/app/providers";
import {ColorSchemeScript} from "@mantine/core";

const instrumentSans = Instrument_Sans({
    subsets: ["latin"]
})

const montserrat = Montserrat({
    subsets: ["latin"],
})

export const metadata: Metadata = {
  title: 'Mantine + Tailwind example',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={instrumentSans.className} style={{
          backgroundColor: "#fff"
      }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
